### ISSUE TITLE
Issue in the displaying of tasks from storage

### ISSUE THREAD

**Issue by Parth-Jain-2002** [akshat1712/To-do-list-Chrome-Extension#1]
var new_text = text.replace(/.{6}/g, "$0\n"); 
This line is producing ambiguous context. Bcz of this, some errors are coming.
![image](https://user-images.githubusercontent.com/72060359/151305767-4753d192-6dc2-435c-af52-9f42b468423f.png)

**Comment by akshat1712** [comment]
How did you get this error? I am not able to replicate this.

**Comment by Parth-Jain-2002** [comment]
Maybe this depends how your browser reads the JavaScript. I tested on Brave and Google Chrome and this error is coming... instead of doing this using this function, maybe you can do it by running a loop which inserts a newline character after every 200 characters

**Comment by Parth-Jain-2002** [comment]
Also the newline character won't process in p tag. So you have to introduce a <br> character in p tag or maybe instead you can use <pre> tag in its place. Pre tag will preserve your line-brakes and spaces

**Comment by Parth-Jain-2002** [comment]
Also the newline character won't process in p tag. So you have to introduce a
character in p tag or maybe instead you can use "pre" tag in its place. Pre tag will preserve your line-brakes and spaces

**Comment by Parth-Jain-2002** [comment]
Also the newline character won't process in p tag. So you have to introduce a "br" character in p tag or maybe instead you can use "pre" tag in its place. Pre tag will preserve your line-brakes and spaces

**Comment by akshat1712** [comment]
okay, I will see to it.

**Comment by akshat1712** [comment]
I have edited the javascript file , please check it once, and tell if there is any abnormalities.

**Comment by Parth-Jain-2002** [comment]
This will work fine
